name: QATest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:ci
        env:
          CYPRESS_RECORD_KEY: ${ eb997c65-f58c-455b-bba2-eb72d0af5cae }


